#env:
#  global:
#    - secure: "c9B/oOzXH5e/lmosV7Ug7F8R1HZPNoSZQrYEj+f5VX9PDs6Lxo0t0agg43epT9NDBN5i+CbL0AR7SbD3gpd6VkYBr7JT64IVhQrF2xEwXuJ0NxnF4PazH5ONRm2guHAvTp3JpozyviCrWJ17IpC81R4VeZTuo5wGMrYDy+xs1O8Xx="
branches:
  only:
  - develop
language: node_js
node_js:
  - "0.10"
before_install:
    - npm install -g grunt-cli
install: 
    - npm install
    - cd readium-js
    - pwd
    - npm install
    - cd ..
before_script:
    - grunt clean
script:
    - grunt test_travis
after_failure: cat ./sauce_connect.log
env:
    global:
        - USE_SAUCE=true
    matrix:
        - MODE=chromeApp
        - MODE=firefox
addons:
  sauce_connect:
    username: "readium"
    access_key: "b0dd7376-7731-47db-bed0-850912b75f2b" 
#    - git log
#    - git reflog
#    - git push "$REPO_URL" develop | grep -v http
