branches:
  only:
  - feature/pluginsX
language: node_js
node_js:
- '0.12'
before_install:
- git submodule update --init --recursive
install:
- npm run prepare
before_script:
- pwd
script:
- cd readium-js/readium-shared-js/readium-cfi-js
- npm run prepare
- npm run build
- npm run test:travis
- cd ../../..
- pwd
- npm run test:travis
after_success:
- echo "node build-config/deployCrx.js"
after_failure: cat ./sauce_connect.log
env:
  global:
  - SAUCE_USERNAME=readium
  - SAUCE_ACCESS_KEY=a36ebc10-e514-4da6-924c-307aec513550
  - USE_SAUCE=true
  - secure: onYFok5CBcV1116+kOEZJsyDB1kRHF+8deU1cll3vhxBEM/woSRvpso32oxjuza+or2uXuBT1SiZn0oTmuKD/TRaKw1e8wTtX6kQzCUhyeGoAyJH8SeGIwkt8+x232rFUe2bNLr6e0JAGZMtTjk1Q1zqfONNWAQzsUWDeUqvwt8=
  matrix:
  - MODE=chromeApp
  - MODE=firefox
addons:
  sauce_connect:
    username: readium
    access_key: a36ebc10-e514-4da6-924c-307aec513550
deploy:
  provider: divshot
  skip_cleanup: true
  environment: development
  on:
    repo: readium/readium-js-viewer
    branch: feature/pluginsX
    condition: "$MODE = firefox"
  api_key:
    secure: dU2zCAnyXFjp5CxDP1TyQrVu0Mg5VG8mcU8wG47MgKwXdh6TBtTGBljowydlwLFHg3VPwdOBwAYR0ysMeU/60wiKy4O9l345fMj3ZqIGMgZsZaTHcaiMUZ06xHPrQviSTb99b6i/2P9csAOdJhwLyS02/2fXm6xsIv+4xyQ3r5o=
