branches:
  only:
  - develop
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install:
- npm install
- cd readium-js
- pwd
- npm install
- cd ..
before_script:
- grunt clean
script:
- grunt test_travis
after_failure: cat ./sauce_connect.log
after_success:
- node deployCrx.js
env:
  global:
  - USE_SAUCE=true
  - secure: onYFok5CBcV1116+kOEZJsyDB1kRHF+8deU1cll3vhxBEM/woSRvpso32oxjuza+or2uXuBT1SiZn0oTmuKD/TRaKw1e8wTtX6kQzCUhyeGoAyJH8SeGIwkt8+x232rFUe2bNLr6e0JAGZMtTjk1Q1zqfONNWAQzsUWDeUqvwt8=
  - secure: AFmLry0PpNfWwDpOtk/Lo4SSNPSiJta8MuJ0zTL9SXdQdY/baFWrQW7GF47C/Tg0Gt1rJL9XZTPbyph8oPR7Okt/RagZegYwBjgrsfxFiZkMAGEzybxDwivlRtQYVk2hsDaxcJw4NjAowVHoN76WmAuD4oYOBbGlfugvSMhnc1k=
  - secure: duDHgHjVH+fVHhEwclGN1op44wGdpAPdPye3ix8aFw+F2jh5hj4RRqD0DLaCpDpxHpPEiaVcYIbPoJC3qbh4c+fmTAIHbIgWHxTFrHuFzwnkFO6+BYrGpbCHam9RPkqurtYbKm6ArWrGz+LBLDYoqRYmsKySAAFLgpegeNOAvI0=
  matrix:
  - MODE=chromeApp
  - MODE=firefox
addons:
  sauce_connect: true
deploy:
  provider: divshot
  skip_cleanup: true
  api_key:
    secure: Y/evg7Yp4WsFjDOJBkQcrJ4/XTQbKYQjdX5iSaHu/JLo/GAJEIqxnEHavprBqHE/KvLjvCStn/bZ15oAMhq+EiJ+VNpZRWmTaZh6SA2CmtJeMtRqUwhpclvbCzSm0Z/8RFHhTmsNh7P5ICuFFWXv/pJ644trfh3Rg8abOIDqvww=
  environment: production
  on:
    repo: readium/readium-js-viewer
    branch: develop
    condition: $MODE = firefox
