branches:
  only:
  - develop
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install:
- npm install
- cd readium-js
- pwd
- npm install
- cd ..
before_script:
- grunt clean
script:
- grunt test_travis
after_failure: cat ./sauce_connect.log
after_success:
- node deployCrx.js
env:
  global:
  - USE_SAUCE=true
  - secure: Qsy3vxTGf84SOhvDHGhhaSqwRrh256JLemn4tamEWIqkUYHgvYHyQsmvgitBCKTYGagG2F6Ag95BbmeKzhTAEhz94awMP3RcVrKxCMjoxmNGj6Mms1Y9310ZgOoSG2Pkz7ydkIzddyW9bGyrLrep4nzWMg3iaE6DU4ZcfhdMAaQ=
  matrix:
  - MODE=chromeApp
  - MODE=firefox
addons:
  sauce_connect:
    username: readium
    access_key: b0dd7376-7731-47db-bed0-850912b75f2b
deploy:
  provider: divshot
  skip_cleanup: true
  api_key:
    secure: Y/evg7Yp4WsFjDOJBkQcrJ4/XTQbKYQjdX5iSaHu/JLo/GAJEIqxnEHavprBqHE/KvLjvCStn/bZ15oAMhq+EiJ+VNpZRWmTaZh6SA2CmtJeMtRqUwhpclvbCzSm0Z/8RFHhTmsNh7P5ICuFFWXv/pJ644trfh3Rg8abOIDqvww=
  environment: production
  on:
    repo: readium/readium-js-viewer
    branch: develop
    condition: $MODE = firefox
